/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Welcome
     * @description Default root route provided by h4ckath0n.
     */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/add/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Finish adding a passkey
     * @description Verify the WebAuthn attestation and attach the new passkey to the user.
     */
    post: operations["add_finish_auth_passkey_add_finish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/add/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start adding a passkey
     * @description Begin adding a new passkey for the authenticated user and return registration options.
     */
    post: operations["add_start_auth_passkey_add_start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Finish passkey login
     * @description Finish passkey login by verifying the WebAuthn assertion for the flow and binding an optional device key.
     */
    post: operations["login_finish_auth_passkey_login_finish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start passkey login
     * @description Begin a username-less passkey login ceremony and return WebAuthn authentication options.
     */
    post: operations["login_start_auth_passkey_login_start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Finish passkey registration
     * @description Finish passkey registration by verifying the WebAuthn attestation for the flow and binding an optional device key.
     */
    post: operations["register_finish_auth_passkey_register_finish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start passkey registration
     * @description Begin a passkey registration ceremony. Creates a new user and a single-use challenge flow, then returns WebAuthn registration options.
     */
    post: operations["register_start_auth_passkey_register_start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkeys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List passkeys
     * @description List all passkeys, including revoked entries, for the current user.
     */
    get: operations["passkeys_list_auth_passkeys_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkeys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Rename a passkey
     * @description Update the user-facing name of a passkey.
     */
    patch: operations["passkey_rename_auth_passkeys__key_id__patch"];
    trace?: never;
  };
  "/auth/passkeys/{key_id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke a passkey
     * @description Revoke a passkey by its internal key ID. The last active passkey cannot be revoked and returns the LAST_PASSKEY error.
     */
    post: operations["passkey_revoke_auth_passkeys__key_id__revoke_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard
     * @description Return all memberships with project info for the current user.
     */
    get: operations["dashboard_dashboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/demo/echo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Demo Echo
     * @description Echo back the message along with its reverse.
     */
    post: operations["demo_echo_demo_echo_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/demo/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Demo Ping
     * @description Simple liveness ping for the demo namespace.
     */
    get: operations["demo_ping_demo_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/demo/sse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Demo Sse
     * @description Authenticated SSE stream that simulates LLM-style output chunks.
     *
     *     Auth: ``Authorization: Bearer <device_jwt>`` with ``aud = h4ckath0n:sse``.
     */
    get: operations["demo_sse_demo_sse_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Basic health check for the app.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Readiness check for E2E and deployment probes.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/activate/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Claim Invite
     * @description Validate invite code, create membership and conversation.
     */
    post: operations["claim_invite_p__project_id__activate_claim_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Event Stream
     * @description SSE stream for real-time events on a project conversation.
     */
    get: operations["event_stream_p__project_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Project Me
     * @description Return membership status, conversation id, and stored email.
     */
    get: operations["project_me_p__project_id__me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Messages
     * @description Return persisted messages for a project conversation.
     */
    get: operations["list_messages_p__project_id__messages_get"];
    put?: never;
    /**
     * Send Message
     * @description Persist user message, run engine turn, persist assistant reply.
     */
    post: operations["send_message_p__project_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/push/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Push Subscribe
     * @description Store a push subscription for the current membership.
     */
    post: operations["push_subscribe_p__project_id__push_subscribe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/push/unsubscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Push Unsubscribe
     * @description Revoke a push subscription by endpoint.
     */
    post: operations["push_unsubscribe_p__project_id__push_unsubscribe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/p/{project_id}/push/vapid-public-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Vapid Public Key
     * @description Return the VAPID public key from environment.
     */
    get: operations["vapid_public_key_p__project_id__push_vapid_public_key_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ClaimRequest */
    ClaimRequest: {
      /** Email */
      email: string;
      /** Invite Code */
      invite_code: string;
    };
    /** ClaimResponse */
    ClaimResponse: {
      /** Conversation Id */
      conversation_id: number;
      /** Membership Status */
      membership_status: string;
      /** Project Id */
      project_id: string;
    };
    /** DashboardResponse */
    DashboardResponse: {
      /** Memberships */
      memberships: components["schemas"]["MembershipInfo"][];
    };
    /** EchoRequest */
    EchoRequest: {
      /** Message */
      message: string;
    };
    /** EchoResponse */
    EchoResponse: {
      /** Message */
      message: string;
      /** Reversed */
      reversed: string;
    };
    /**
     * ErrorResponse
     * @description Standard error envelope for auth routes.
     */
    ErrorResponse: {
      /**
       * Detail
       * @description Error detail message or structured error payload.
       */
      detail:
        | string
        | {
            [key: string]: string;
          };
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @description Health status string.
       */
      status: string;
    };
    /** MeResponse */
    MeResponse: {
      /** Conversation Id */
      conversation_id?: number | null;
      /** Email */
      email?: string | null;
      /** Membership Status */
      membership_status: string;
    };
    /** MembershipInfo */
    MembershipInfo: {
      /** Conversation Id */
      conversation_id?: number | null;
      /** Display Name */
      display_name?: string | null;
      /** Project Id */
      project_id: string;
      /** Status */
      status: string;
    };
    /** MessageItem */
    MessageItem: {
      /** Content */
      content: string;
      /** Created At */
      created_at: string;
      /** Message Id */
      message_id: number;
      /** Role */
      role: string;
      /** Server Msg Id */
      server_msg_id: string;
    };
    /** MessageListResponse */
    MessageListResponse: {
      /** Messages */
      messages: components["schemas"]["MessageItem"][];
    };
    /** PasskeyAddFinishRequest */
    PasskeyAddFinishRequest: {
      /**
       * Credential
       * @description Browser PublicKeyCredential response as JSON.
       */
      credential: {
        [key: string]: unknown;
      };
      /**
       * Device Label
       * @description Optional label for the device.
       */
      device_label?: string | null;
      /**
       * Device Public Key Jwk
       * @description Optional device public key in JWK format to bind a device identity.
       */
      device_public_key_jwk?: {
        [key: string]: unknown;
      } | null;
      /**
       * Flow Id
       * @description Flow ID returned by add/start.
       */
      flow_id: string;
    };
    /** PasskeyAddStartResponse */
    PasskeyAddStartResponse: {
      /**
       * Flow Id
       * @description Server-generated flow ID for add passkey.
       */
      flow_id: string;
      /**
       * Options
       * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
       */
      options: {
        [key: string]: unknown;
      };
    };
    /** PasskeyFinishResponse */
    PasskeyFinishResponse: {
      /**
       * Device Id
       * @description Device ID that starts with the d prefix, empty when no device key is bound.
       */
      device_id: string;
      /**
       * Display Name
       * @description Optional display name for the user, not set by default.
       */
      display_name?: string | null;
      /**
       * Role
       * @description Server-side role for the user.
       */
      role: string;
      /**
       * User Id
       * @description User ID that starts with the u prefix.
       */
      user_id: string;
    };
    /** PasskeyInfo */
    PasskeyInfo: {
      /**
       * Created At
       * Format: date-time
       * @description Creation timestamp in UTC.
       */
      created_at: string;
      /**
       * Id
       * @description Internal passkey ID that starts with the k prefix.
       */
      id: string;
      /**
       * Last Used At
       * @description Last successful use timestamp.
       */
      last_used_at?: string | null;
      /**
       * Name
       * @description User-provided passkey name.
       */
      name?: string | null;
      /**
       * Revoked At
       * @description Revocation timestamp, if revoked.
       */
      revoked_at?: string | null;
    };
    /** PasskeyListResponse */
    PasskeyListResponse: {
      /**
       * Passkeys
       * @description Passkeys for the current user.
       */
      passkeys: components["schemas"]["PasskeyInfo"][];
    };
    /** PasskeyLoginFinishRequest */
    PasskeyLoginFinishRequest: {
      /**
       * Credential
       * @description Browser PublicKeyCredential response as JSON.
       */
      credential: {
        [key: string]: unknown;
      };
      /**
       * Device Label
       * @description Optional label for the device.
       */
      device_label?: string | null;
      /**
       * Device Public Key Jwk
       * @description Optional device public key in JWK format to bind a device identity.
       */
      device_public_key_jwk?: {
        [key: string]: unknown;
      } | null;
      /**
       * Flow Id
       * @description Flow ID returned by login/start.
       */
      flow_id: string;
    };
    /** PasskeyLoginStartResponse */
    PasskeyLoginStartResponse: {
      /**
       * Flow Id
       * @description Server-generated flow ID for login.
       */
      flow_id: string;
      /**
       * Options
       * @description PublicKeyCredentialRequestOptions payload as a JSON-safe dict.
       */
      options: {
        [key: string]: unknown;
      };
    };
    /** PasskeyRegisterFinishRequest */
    PasskeyRegisterFinishRequest: {
      /**
       * Credential
       * @description Browser PublicKeyCredential response as JSON.
       */
      credential: {
        [key: string]: unknown;
      };
      /**
       * Device Label
       * @description Optional label for the device.
       */
      device_label?: string | null;
      /**
       * Device Public Key Jwk
       * @description Optional device public key in JWK format to bind a device identity.
       */
      device_public_key_jwk?: {
        [key: string]: unknown;
      } | null;
      /**
       * Flow Id
       * @description Flow ID returned by register/start.
       */
      flow_id: string;
    };
    /** PasskeyRegisterStartResponse */
    PasskeyRegisterStartResponse: {
      /**
       * Flow Id
       * @description Server-generated flow ID for registration.
       */
      flow_id: string;
      /**
       * Options
       * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
       */
      options: {
        [key: string]: unknown;
      };
    };
    /** PasskeyRenameRequest */
    PasskeyRenameRequest: {
      /**
       * Name
       * @description New passkey name. Null or empty to clear.
       */
      name?: string | null;
    };
    /** PasskeyRenameResponse */
    PasskeyRenameResponse: {
      /**
       * Id
       * @description Internal passkey ID.
       */
      id: string;
      /**
       * Name
       * @description Updated passkey name.
       */
      name?: string | null;
    };
    /** PasskeyRevokeResponse */
    PasskeyRevokeResponse: {
      /**
       * Message
       * @description Status message for the revocation action.
       */
      message: string;
    };
    /** PingResponse */
    PingResponse: {
      /** Ok */
      ok: boolean;
    };
    /** PushSubscribeRequest */
    PushSubscribeRequest: {
      /** Endpoint */
      endpoint: string;
      /** Keys */
      keys: {
        [key: string]: string;
      };
      /** User Agent */
      user_agent?: string | null;
    };
    /** PushSubscribeResponse */
    PushSubscribeResponse: {
      /** Subscription Id */
      subscription_id: number;
    };
    /** PushUnsubscribeRequest */
    PushUnsubscribeRequest: {
      /** Endpoint */
      endpoint: string;
    };
    /** PushUnsubscribeResponse */
    PushUnsubscribeResponse: {
      /** Ok */
      ok: boolean;
    };
    /** RootResponse */
    RootResponse: {
      /**
       * Message
       * @description Welcome message.
       */
      message: string;
    };
    /** SendMessageRequest */
    SendMessageRequest: {
      /** Client Msg Id */
      client_msg_id?: string | null;
      /** Text */
      text: string;
    };
    /** SendMessageResponse */
    SendMessageResponse: {
      /** Content */
      content: string;
      /** Message Id */
      message_id: number;
      /** Role */
      role: string;
      /** Server Msg Id */
      server_msg_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VapidPublicKeyResponse */
    VapidPublicKeyResponse: {
      /** Public Key */
      public_key: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RootResponse"];
        };
      };
    };
  };
  add_finish_auth_passkey_add_finish_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasskeyAddFinishRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyFinishResponse"];
        };
      };
      /** @description Invalid or expired flow, or WebAuthn verification error. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_start_auth_passkey_add_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyAddStartResponse"];
        };
      };
      /** @description Missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login_finish_auth_passkey_login_finish_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasskeyLoginFinishRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyFinishResponse"];
        };
      };
      /** @description Invalid credentials, revoked passkey, or expired flow. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_start_auth_passkey_login_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyLoginStartResponse"];
        };
      };
    };
  };
  register_finish_auth_passkey_register_finish_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasskeyRegisterFinishRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyFinishResponse"];
        };
      };
      /** @description Invalid or expired flow, or invalid WebAuthn payload. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_start_auth_passkey_register_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyRegisterStartResponse"];
        };
      };
      /** @description Invalid request or WebAuthn configuration error. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  passkeys_list_auth_passkeys_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyListResponse"];
        };
      };
      /** @description Missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  passkey_rename_auth_passkeys__key_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasskeyRenameRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyRenameResponse"];
        };
      };
      /** @description Missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Passkey not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot rename a revoked passkey. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation error. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  passkey_revoke_auth_passkeys__key_id__revoke_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasskeyRevokeResponse"];
        };
      };
      /** @description Missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Passkey not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot revoke the last active passkey. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "detail": {
           *         "code": "LAST_PASSKEY",
           *         "message": "Cannot revoke the last active passkey."
           *       }
           *     }
           */
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dashboard_dashboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DashboardResponse"];
        };
      };
    };
  };
  demo_echo_demo_echo_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EchoRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EchoResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  demo_ping_demo_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PingResponse"];
        };
      };
    };
  };
  demo_sse_demo_sse_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  claim_invite_p__project_id__activate_claim_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClaimRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClaimResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  event_stream_p__project_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  project_me_p__project_id__me_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_messages_p__project_id__messages_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_message_p__project_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SendMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  push_subscribe_p__project_id__push_subscribe_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSubscribeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PushSubscribeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  push_unsubscribe_p__project_id__push_unsubscribe_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushUnsubscribeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PushUnsubscribeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  vapid_public_key_p__project_id__push_vapid_public_key_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VapidPublicKeyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
